### ISSUE TITLE
Pep-8 compliant

### ISSUE THREAD

**Issue by akebrissman** [akebrissman/sniffer#3]
The python code in sniffer/src should be pep-8 compliant.

**Comment by mblomdahl** [comment]
@akebrissman: Feel free marking me as *assignee* for this issue, along with #1 and #2. This makes the issues show up under my **Issues** pane.

![image](https://cloud.githubusercontent.com/assets/786326/9567240/1ebf1166-4f24-11e5-9b56-86bd457e6ea3.png)

**Comment by mblomdahl** [comment]
Created feature branch ``pep-8-compliance`` in forked repo, here: https://github.com/mblomdahl/sniffer/tree/feature/pep-8-compliance

This is where I would attempt solving issue #3, before submitting a pull request to your upstream repository.
